# Generated by Django 6.0.5 on 2026-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('kasir', 'Kasir'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=10),
        ),
    ]
