# Generated by Django 6.0.4 on 2026-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
