# Generated by Django 6.0.4 on 2026-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Warkop Level Up Masashimura', max_length=255)),
                ('hero_subheadline', models.TextField(default='Tempat nongkrong kasual modern di Bekasi dengan cita rasa nikmat.')),
                ('hero_food_image', models.URLField(blank=True, max_length=500, null=True)),
                ('marquee_text', models.TextField(default='MASA SIH MURAH? • WARKOP EVOLUTION • GOOD FOOD • GOOD VIBES')),
                ('about_text', models.TextField(default='Masashimura adalah sebuah usaha kuliner personal asal Bekasi...')),
                ('about_image', models.URLField(blank=True, max_length=500, null=True)),
                ('metric_1', models.CharField(default='2024', max_length=50)),
                ('metric_2', models.CharField(default='50+', max_length=50)),
                ('metric_3', models.CharField(default='★★★★★', max_length=50)),
                ('bento_text_1', models.CharField(default='Nyaman Maksimal', max_length=100)),
                ('bento_text_2', models.CharField(default='Nongkrong Sampai Larut Malam', max_length=100)),
                ('bento_wifi', models.CharField(default='WiFi 150Mbps', max_length=100)),
                ('bento_colokan', models.CharField(default='Banyak Colokan', max_length=100)),
            ],
        ),
    ]
