# Generated by Django 6.0.4 on 2026-06-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentoFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contoh: Nyaman Maksimal, Banyak Colokan, WiFi 150Mbps', max_length=100)),
                ('icon_name', models.CharField(default='Wifi', help_text='Nama icon dari library Lucide / FontAwesome yang dipake di Vue (misal: Wifi, Plug, Coffee, Shield)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Urutan penataan box bento di frontend')),
            ],
            options={
                'verbose_name': 'Bento Facility',
                'verbose_name_plural': 'Bento Facilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryLookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Nama produk pakaian atau judul foto suasana', max_length=100, null=True)),
                ('image_url', models.URLField(help_text='Link URL gambar secure dari Cloudinary', max_length=500)),
                ('category', models.CharField(default='General', help_text="Kategori (misal: 'Suasana Kedai', 'Lookbook Kalren', 'Best Seller')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Lookbook',
                'verbose_name_plural': 'Gallery Lookbooks',
            },
        ),
        migrations.AlterModelOptions(
            name='homepageconfig',
            options={'verbose_name': 'Homepage Configuration'},
        ),
        migrations.RemoveField(
            model_name='homepageconfig',
            name='bento_colokan',
        ),
        migrations.RemoveField(
            model_name='homepageconfig',
            name='bento_text_1',
        ),
        migrations.RemoveField(
            model_name='homepageconfig',
            name='bento_text_2',
        ),
        migrations.RemoveField(
            model_name='homepageconfig',
            name='bento_wifi',
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='about_text',
            field=models.TextField(blank=True, default='Masashimura adalah sebuah usaha kuliner personal asal Bekasi...', null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_headline',
            field=models.CharField(blank=True, default='Warkop Level Up Masashimura', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_subheadline',
            field=models.TextField(blank=True, default='Tempat nongkrong kasual modern di Bekasi dengan cita rasa nikmat.', null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='marquee_text',
            field=models.TextField(blank=True, default='MASA SIH MURAH? • WARKOP EVOLUTION • GOOD FOOD • GOOD VIBES', null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='metric_1',
            field=models.CharField(blank=True, default='2024', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='metric_2',
            field=models.CharField(blank=True, default='50+', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='metric_3',
            field=models.CharField(blank=True, default='★★★★★', max_length=50, null=True),
        ),
    ]
