# Generated by Django 6.0.4 on 2026-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_bentofacility_gallerylookbook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bentofacility',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='bentofacility',
            name='size',
            field=models.CharField(choices=[('normal', 'Standard Card (1x1)'), ('large', 'Large Card (2x2)')], default='normal', help_text='Mengatur tata ruang kotak di frontend', max_length=10),
        ),
        migrations.AlterField(
            model_name='bentofacility',
            name='icon_name',
            field=models.CharField(default='Wifi', help_text='Nama icon Lucide (contoh: Wifi, Coffee, Zap, Utensils, DollarSign, Moon)', max_length=50),
        ),
        migrations.AlterField(
            model_name='bentofacility',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bentofacility',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
