# Generated by Django 6.0.4 on 2026-06-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_bentofacility_options_bentofacility_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='hero_bg_image',
            field=models.URLField(blank=True, help_text='Foto background parallax hero (16:9)', null=True),
        ),
    ]
