# Generated by Django 6.0.5 on 2026-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tunai'), ('qris', 'QRIS')], default='cash', max_length=10),
        ),
    ]
