# Generated by Django 6.0.5 on 2026-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Telepon')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Qty Pesanan')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Belanja')),
                ('last_order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_wa_receiver', models.CharField(default='628xxx', max_length=20, verbose_name='WA Admin')),
                ('min_orders_requirement', models.IntegerField(default=10, verbose_name='Min. Pesanan')),
                ('min_spending_requirement', models.DecimalField(decimal_places=0, default=200000, max_digits=12, verbose_name='Min. Belanja')),
                ('discount_percentage', models.IntegerField(default=10, verbose_name='Diskon (%)')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_wa', models.CharField(max_length=20)),
                ('menu_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
