# Generated by Django 6.0.5 on 2026-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_customer_order_orderitem_delete_loyaltyprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('wa', 'WhatsApp'), ('qris', 'QRIS')], max_length=20),
        ),
    ]
