# Generated by Django 6.0.4 on 2026-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='admin_wa_receiver',
            field=models.CharField(default='628xxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='discount_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='min_orders_requirement',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qris', 'QRIS')], max_length=20),
        ),
    ]
