# Generated by Django 6.0.4 on 2026-06-22 15:31
# PATCHED: tambah data migration untuk isi order_number unik
# sebelum unique constraint diterapkan, agar tidak UNIQUE constraint failed
# pada baris Order lama yang order_number-nya masih kosong.

import django.db.models.deletion
from django.db import migrations, models
import random
import string
from datetime import datetime


def fill_order_numbers(apps, schema_editor):
    """Isi order_number untuk semua Order yang masih kosong."""
    Order = apps.get_model('order', 'Order')
    used = set()

    for order in Order.objects.all():
        # Sudah ada order_number-nya (tidak mungkin di tahap ini,
        # tapi jaga-jaga kalau ada partial migration)
        if getattr(order, 'order_number', ''):
            used.add(order.order_number)
            continue

        # Generate kode unik MSM-YYMMDD-XXXX
        date_part = order.created_at.strftime("%y%m%d") if hasattr(order, 'created_at') and order.created_at else datetime.now().strftime("%y%m%d")
        while True:
            random_part = "".join(random.choices(string.ascii_uppercase + string.digits, k=4))
            code = f"MSM-{date_part}-{random_part}"
            if code not in used:
                used.add(code)
                break

        order.order_number = code
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menu_image_url_menu_image'),
        ('order', '0004_expense_orderitem_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('special_discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Diskon manual dari admin, override aturan umum loyalty', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_orders', models.PositiveIntegerField(default=10, help_text='Minimal jumlah pesanan dalam periode')),
                ('min_spending', models.DecimalField(decimal_places=0, default=100000, help_text='Minimal total belanja dalam periode (Rp)', max_digits=12)),
                ('period_days', models.PositiveIntegerField(default=30, help_text='Periode pengecekan (hari)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10, help_text='Diskon otomatis untuk LOYAL MEMBER (%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='LoyaltySetting',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deferred_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),

        # PATCH: tambah order_number dulu TANPA unique constraint
        # supaya bisa diisi nilainya terlebih dahulu
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, default=''),
        ),

        # PATCH: isi order_number untuk semua baris lama
        migrations.RunPython(fill_order_numbers, migrations.RunPython.noop),

        # PATCH: baru setelah terisi semua, terapkan unique constraint
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),

        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('pos', 'POS')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('qris', 'QRIS'), ('gateway', 'Payment Gateway')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]