# Generated by Django 6.0.4 on 2026-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_customerloyalty_loyaltysettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerloyalty',
            options={'ordering': ['-total_spent'], 'verbose_name': 'Customer Loyalty', 'verbose_name_plural': 'Customer Loyalties'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerloyalty',
            name='special_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diskon manual dari admin — override aturan umum loyalty', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deferred_payment',
            field=models.BooleanField(default=False, help_text='POS: pelanggan makan dulu, bayar nanti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('qris', 'QRIS'), ('qris_manual', 'QRIS Manual'), ('gateway', 'Payment Gateway')], max_length=15, null=True),
        ),
    ]
