# Generated by Django 6.0.4 on 2026-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_customerloyalty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
