# Generated by Django 6.0.4 on 2026-06-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_amount_paid_order_change_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kasir_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
