# Generated by Django 6.0.4 on 2026-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_kasir_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_whatsapp', models.CharField(blank=True, default='', help_text='Nomor WA admin format internasional tanpa +, cth: 628xxx', max_length=20)),
                ('is_open_override', models.BooleanField(blank=True, default=None, help_text='null=jadwal, True=paksa buka, False=paksa tutup', null=True)),
                ('closed_message', models.TextField(default='Maaf, kami sedang tidak beroperasi. Silakan kembali sesuai jam operasional kami.', help_text='Pesan yang ditampilkan saat toko tutup')),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Jadwal per hari. Key 0-6 (0=Senin), value: {open, close} atau null')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
