# Generated by Django 6.0.5 on 2026-07-12 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_category_name_alter_menu_category'),
        ('order', '0014_orderpayment_split_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_point_redemption',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PointReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_cost', models.PositiveIntegerField(help_text='Jumlah poin yang dibutuhkan buat nuker 1 menu ini')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rewards', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Point Reward',
                'verbose_name_plural': 'Point Rewards',
                'ordering': ['point_cost'],
            },
        ),
    ]
