# Generated by Django 6.0.5 on 2026-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_is_point_redemption_pointreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='rupiah_per_point',
            field=models.PositiveIntegerField(default=10000, help_text='Nominal belanja (Rp) yang setara dengan 1 poin loyalty'),
        ),
    ]
