# Generated by Django 6.0.4 on 2026-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('order_source', models.CharField(max_length=10)),
                ('order_status', models.CharField(max_length=15)),
                ('payment_status', models.CharField(max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('original_created_at', models.DateTimeField()),
                ('items_snapshot', models.JSONField(default=list)),
                ('payments_snapshot', models.JSONField(default=list)),
                ('loyalty_points_reverted', models.IntegerField(default=0, help_text='Poin yang ditarik balik dari CustomerLoyalty (0 kalau order ini memang tidak pernah menyumbang poin)')),
                ('loyalty_clamped', models.BooleanField(default=False, help_text='True kalau saldo poin customer sudah lebih kecil dari yang seharusnya di-reverse (kemungkinan poinnya sudah kepakai buat redeem reward lain) — dikliping ke 0, bukan dipaksa minus')),
                ('promo_code_reverted', models.CharField(blank=True, default='', max_length=50)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Deletion Log',
                'verbose_name_plural': 'Order Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_applied',
            field=models.BooleanField(default=False, help_text='True kalau order ini sudah pernah trigger penambahan poin ke customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Poin yang di-earn dari order ini saat completed — disimpan biar reversal saat delete akurat, tidak bergantung rupiah_per_point yang mungkin sudah berubah'),
        ),
    ]
