# Generated by Django 6.0.4 on 2026-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_orderdeletionlog_order_loyalty_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_image_url',
            field=models.URLField(blank=True, default='', help_text='Bukti pembayaran QRIS (link Cloudinary), diisi saat checkout web QRIS', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending'), ('pending_verification', 'Menunggu Verifikasi'), ('void', 'Batal')], default='unpaid', max_length=25),
        ),
    ]
