# Generated by Django 6.0.5 on 2026-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_proof_image_url_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeletionlog',
            name='payment_status',
            field=models.CharField(max_length=25),
        ),
    ]
