# Generated by Django 6.0.4 on 2026-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_fix_deletionlog_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
