# Generated by Django 6.0.5 on 2026-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_entered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proof_image_url',
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_snap_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending'), ('void', 'Batal')], default='unpaid', max_length=25),
        ),
    ]
