# Generated by Django 6.0.5 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_order_proof_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
