# Generated by Django 6.0.4 on 2026-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_remove_menu_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='stock',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]