# Generated by Django 6.0.4 on 2026-06-22 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]