# Generated by Django 6.0.4 on 2026-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menu_image_url_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price_web',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
