# Generated by Django 6.0.4 on 2026-06-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_add_price_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('makanan', 'Makanan'), ('snack', 'Snack'), ('minuman', 'Minuman')], default='makanan', max_length=20),
        ),
    ]
