# Generated by Django 6.0.5 on 2026-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_category_name_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
